/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AnimateExtended
 */
public class AnimateExtendedTest {
    private final AnimateExtended model = new AnimateExtended();

    /**
     * Model tests for AnimateExtended
     */
    @Test
    public void testAnimateExtended() {
        // TODO: test AnimateExtended
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'videoUrl'
     */
    @Test
    public void videoUrlTest() {
        // TODO: test videoUrl
    }

    /**
     * Test the property 'audioUrl'
     */
    @Test
    public void audioUrlTest() {
        // TODO: test audioUrl
    }

    /**
     * Test the property 'transcriptUrl'
     */
    @Test
    public void transcriptUrlTest() {
        // TODO: test transcriptUrl
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'creditsDeducted'
     */
    @Test
    public void creditsDeductedTest() {
        // TODO: test creditsDeducted
    }

}
