/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AnimateDto
 */
public class AnimateDtoTest {
    private final AnimateDto model = new AnimateDto();

    /**
     * Model tests for AnimateDto
     */
    @Test
    public void testAnimateDto() {
        // TODO: test AnimateDto
    }

    /**
     * Test the property 'videoUrl'
     */
    @Test
    public void videoUrlTest() {
        // TODO: test videoUrl
    }

    /**
     * Test the property 'transcript'
     */
    @Test
    public void transcriptTest() {
        // TODO: test transcript
    }

    /**
     * Test the property 'voiceId'
     */
    @Test
    public void voiceIdTest() {
        // TODO: test voiceId
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'maxCredits'
     */
    @Test
    public void maxCreditsTest() {
        // TODO: test maxCredits
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

}
