/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LipsyncDto
 */
public class LipsyncDtoTest {
    private final LipsyncDto model = new LipsyncDto();

    /**
     * Model tests for LipsyncDto
     */
    @Test
    public void testLipsyncDto() {
        // TODO: test LipsyncDto
    }

    /**
     * Test the property 'audioUrl'
     */
    @Test
    public void audioUrlTest() {
        // TODO: test audioUrl
    }

    /**
     * Test the property 'videoUrl'
     */
    @Test
    public void videoUrlTest() {
        // TODO: test videoUrl
    }

    /**
     * Test the property 'synergize'
     */
    @Test
    public void synergizeTest() {
        // TODO: test synergize
    }

    /**
     * Test the property 'maxCredits'
     */
    @Test
    public void maxCreditsTest() {
        // TODO: test maxCredits
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

}
