/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LipSyncExtended
 */
public class LipSyncExtendedTest {
    private final LipSyncExtended model = new LipSyncExtended();

    /**
     * Model tests for LipSyncExtended
     */
    @Test
    public void testLipSyncExtended() {
        // TODO: test LipSyncExtended
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'originalVideoUrl'
     */
    @Test
    public void originalVideoUrlTest() {
        // TODO: test originalVideoUrl
    }

    /**
     * Test the property 'originalAudioUrl'
     */
    @Test
    public void originalAudioUrlTest() {
        // TODO: test originalAudioUrl
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'synergize'
     */
    @Test
    public void synergizeTest() {
        // TODO: test synergize
    }

    /**
     * Test the property 'creditsDeducted'
     */
    @Test
    public void creditsDeductedTest() {
        // TODO: test creditsDeducted
    }

}
