/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TranslationJobExtended
 */
public class TranslationJobExtendedTest {
    private final TranslationJobExtended model = new TranslationJobExtended();

    /**
     * Model tests for TranslationJobExtended
     */
    @Test
    public void testTranslationJobExtended() {
        // TODO: test TranslationJobExtended
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'videoUrl'
     */
    @Test
    public void videoUrlTest() {
        // TODO: test videoUrl
    }

    /**
     * Test the property 'audioUrl'
     */
    @Test
    public void audioUrlTest() {
        // TODO: test audioUrl
    }

    /**
     * Test the property 'transcriptUrl'
     */
    @Test
    public void transcriptUrlTest() {
        // TODO: test transcriptUrl
    }

    /**
     * Test the property 'originalVideoUrl'
     */
    @Test
    public void originalVideoUrlTest() {
        // TODO: test originalVideoUrl
    }

    /**
     * Test the property 'sourceLanguage'
     */
    @Test
    public void sourceLanguageTest() {
        // TODO: test sourceLanguage
    }

    /**
     * Test the property 'targetLanguage'
     */
    @Test
    public void targetLanguageTest() {
        // TODO: test targetLanguage
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'step'
     */
    @Test
    public void stepTest() {
        // TODO: test step
    }

}
