/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * LipsyncDto
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class LipsyncDto {
  public static final String SERIALIZED_NAME_AUDIO_URL = "audioUrl";
  @SerializedName(SERIALIZED_NAME_AUDIO_URL)
  private String audioUrl;

  public static final String SERIALIZED_NAME_VIDEO_URL = "videoUrl";
  @SerializedName(SERIALIZED_NAME_VIDEO_URL)
  private String videoUrl;

  public static final String SERIALIZED_NAME_SYNERGIZE = "synergize";
  @SerializedName(SERIALIZED_NAME_SYNERGIZE)
  private Boolean synergize = true;

  public static final String SERIALIZED_NAME_MAX_CREDITS = "maxCredits";
  @SerializedName(SERIALIZED_NAME_MAX_CREDITS)
  private Double maxCredits;

  public static final String SERIALIZED_NAME_WEBHOOK_URL = "webhookUrl";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_URL)
  private String webhookUrl;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  private String model = "sync-1.5.0";

  public LipsyncDto() {
  }

  public LipsyncDto audioUrl(String audioUrl) {
    
    
    
    
    this.audioUrl = audioUrl;
    return this;
  }

   /**
   * A url to the audio file to be synchronized -- must be publicly accessible
   * @return audioUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A url to the audio file to be synchronized -- must be publicly accessible")

  public String getAudioUrl() {
    return audioUrl;
  }


  public void setAudioUrl(String audioUrl) {
    
    
    
    this.audioUrl = audioUrl;
  }


  public LipsyncDto videoUrl(String videoUrl) {
    
    
    
    
    this.videoUrl = videoUrl;
    return this;
  }

   /**
   * A url to the video file to be synchronized -- must be publicly accessible
   * @return videoUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A url to the video file to be synchronized -- must be publicly accessible")

  public String getVideoUrl() {
    return videoUrl;
  }


  public void setVideoUrl(String videoUrl) {
    
    
    
    this.videoUrl = videoUrl;
  }


  public LipsyncDto synergize(Boolean synergize) {
    
    
    
    
    this.synergize = synergize;
    return this;
  }

   /**
   * A flag to enable / disable post-processing
   * @return synergize
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "A flag to enable / disable post-processing")

  public Boolean getSynergize() {
    return synergize;
  }


  public void setSynergize(Boolean synergize) {
    
    
    
    this.synergize = synergize;
  }


  public LipsyncDto maxCredits(Double maxCredits) {
    
    
    
    
    this.maxCredits = maxCredits;
    return this;
  }

  public LipsyncDto maxCredits(Integer maxCredits) {
    
    
    
    
    this.maxCredits = maxCredits.doubleValue();
    return this;
  }

   /**
   * Maximum number of credits to use for video generation. If job exceeds this value, the job will be aborted
   * @return maxCredits
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Maximum number of credits to use for video generation. If job exceeds this value, the job will be aborted")

  public Double getMaxCredits() {
    return maxCredits;
  }


  public void setMaxCredits(Double maxCredits) {
    
    
    
    this.maxCredits = maxCredits;
  }


  public LipsyncDto webhookUrl(String webhookUrl) {
    
    
    
    
    this.webhookUrl = webhookUrl;
    return this;
  }

   /**
   * A url to send a notification to upon completion of video generation
   * @return webhookUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A url to send a notification to upon completion of video generation")

  public String getWebhookUrl() {
    return webhookUrl;
  }


  public void setWebhookUrl(String webhookUrl) {
    
    
    
    this.webhookUrl = webhookUrl;
  }


  public LipsyncDto model(String model) {
    
    
    
    
    this.model = model;
    return this;
  }

   /**
   * The model to use for video generation
   * @return model
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "sync-1.5.0", value = "The model to use for video generation")

  public String getModel() {
    return model;
  }


  public void setModel(String model) {
    
    
    
    this.model = model;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the LipsyncDto instance itself
   */
  public LipsyncDto putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LipsyncDto lipsyncDto = (LipsyncDto) o;
    return Objects.equals(this.audioUrl, lipsyncDto.audioUrl) &&
        Objects.equals(this.videoUrl, lipsyncDto.videoUrl) &&
        Objects.equals(this.synergize, lipsyncDto.synergize) &&
        Objects.equals(this.maxCredits, lipsyncDto.maxCredits) &&
        Objects.equals(this.webhookUrl, lipsyncDto.webhookUrl) &&
        Objects.equals(this.model, lipsyncDto.model)&&
        Objects.equals(this.additionalProperties, lipsyncDto.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(audioUrl, videoUrl, synergize, maxCredits, webhookUrl, model, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LipsyncDto {\n");
    sb.append("    audioUrl: ").append(toIndentedString(audioUrl)).append("\n");
    sb.append("    videoUrl: ").append(toIndentedString(videoUrl)).append("\n");
    sb.append("    synergize: ").append(toIndentedString(synergize)).append("\n");
    sb.append("    maxCredits: ").append(toIndentedString(maxCredits)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("audioUrl");
    openapiFields.add("videoUrl");
    openapiFields.add("synergize");
    openapiFields.add("maxCredits");
    openapiFields.add("webhookUrl");
    openapiFields.add("model");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("audioUrl");
    openapiRequiredFields.add("videoUrl");
    openapiRequiredFields.add("synergize");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LipsyncDto
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LipsyncDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LipsyncDto is not found in the empty JSON string", LipsyncDto.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LipsyncDto.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("audioUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audioUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audioUrl").toString()));
      }
      if (!jsonObj.get("videoUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `videoUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("videoUrl").toString()));
      }
      if ((jsonObj.get("webhookUrl") != null && !jsonObj.get("webhookUrl").isJsonNull()) && !jsonObj.get("webhookUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `webhookUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("webhookUrl").toString()));
      }
      if ((jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) && !jsonObj.get("model").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `model` to be a primitive type in the JSON string but got `%s`", jsonObj.get("model").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LipsyncDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LipsyncDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LipsyncDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LipsyncDto.class));

       return (TypeAdapter<T>) new TypeAdapter<LipsyncDto>() {
           @Override
           public void write(JsonWriter out, LipsyncDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public LipsyncDto read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             LipsyncDto instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LipsyncDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LipsyncDto
  * @throws IOException if the JSON string is invalid with respect to LipsyncDto
  */
  public static LipsyncDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LipsyncDto.class);
  }

 /**
  * Convert an instance of LipsyncDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

