/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TranslationJobExtended
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TranslationJobExtended {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_VIDEO_URL = "video_url";
  @SerializedName(SERIALIZED_NAME_VIDEO_URL)
  private String videoUrl;

  public static final String SERIALIZED_NAME_AUDIO_URL = "audio_url";
  @SerializedName(SERIALIZED_NAME_AUDIO_URL)
  private String audioUrl;

  public static final String SERIALIZED_NAME_TRANSCRIPT_URL = "transcript_url";
  @SerializedName(SERIALIZED_NAME_TRANSCRIPT_URL)
  private String transcriptUrl;

  public static final String SERIALIZED_NAME_ORIGINAL_VIDEO_URL = "original_video_url";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_VIDEO_URL)
  private String originalVideoUrl;

  public static final String SERIALIZED_NAME_SOURCE_LANGUAGE = "source_language";
  @SerializedName(SERIALIZED_NAME_SOURCE_LANGUAGE)
  private String sourceLanguage;

  public static final String SERIALIZED_NAME_TARGET_LANGUAGE = "target_language";
  @SerializedName(SERIALIZED_NAME_TARGET_LANGUAGE)
  private String targetLanguage;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STEP = "step";
  @SerializedName(SERIALIZED_NAME_STEP)
  private String step;

  public TranslationJobExtended() {
  }

  public TranslationJobExtended id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * A unique identifier for the translation job.
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A unique identifier for the translation job.")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public TranslationJobExtended videoUrl(String videoUrl) {
    
    
    
    
    this.videoUrl = videoUrl;
    return this;
  }

   /**
   * A URL which can be used to download the video.
   * @return videoUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A URL which can be used to download the video.")

  public String getVideoUrl() {
    return videoUrl;
  }


  public void setVideoUrl(String videoUrl) {
    
    
    
    this.videoUrl = videoUrl;
  }


  public TranslationJobExtended audioUrl(String audioUrl) {
    
    
    
    
    this.audioUrl = audioUrl;
    return this;
  }

   /**
   * A URL which can be used to download the audio.
   * @return audioUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A URL which can be used to download the audio.")

  public String getAudioUrl() {
    return audioUrl;
  }


  public void setAudioUrl(String audioUrl) {
    
    
    
    this.audioUrl = audioUrl;
  }


  public TranslationJobExtended transcriptUrl(String transcriptUrl) {
    
    
    
    
    this.transcriptUrl = transcriptUrl;
    return this;
  }

   /**
   * A URL to access the transcript of the video.
   * @return transcriptUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A URL to access the transcript of the video.")

  public String getTranscriptUrl() {
    return transcriptUrl;
  }


  public void setTranscriptUrl(String transcriptUrl) {
    
    
    
    this.transcriptUrl = transcriptUrl;
  }


  public TranslationJobExtended originalVideoUrl(String originalVideoUrl) {
    
    
    
    
    this.originalVideoUrl = originalVideoUrl;
    return this;
  }

   /**
   * The original URL of the video that was submitted.
   * @return originalVideoUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The original URL of the video that was submitted.")

  public String getOriginalVideoUrl() {
    return originalVideoUrl;
  }


  public void setOriginalVideoUrl(String originalVideoUrl) {
    
    
    
    this.originalVideoUrl = originalVideoUrl;
  }


  public TranslationJobExtended sourceLanguage(String sourceLanguage) {
    
    
    
    
    this.sourceLanguage = sourceLanguage;
    return this;
  }

   /**
   * The source language of the video.
   * @return sourceLanguage
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The source language of the video.")

  public String getSourceLanguage() {
    return sourceLanguage;
  }


  public void setSourceLanguage(String sourceLanguage) {
    
    
    
    this.sourceLanguage = sourceLanguage;
  }


  public TranslationJobExtended targetLanguage(String targetLanguage) {
    
    
    
    
    this.targetLanguage = targetLanguage;
    return this;
  }

   /**
   * The language into which the video is being translated.
   * @return targetLanguage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The language into which the video is being translated.")

  public String getTargetLanguage() {
    return targetLanguage;
  }


  public void setTargetLanguage(String targetLanguage) {
    
    
    
    this.targetLanguage = targetLanguage;
  }


  public TranslationJobExtended status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * The status of the translation job.
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The status of the translation job.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public TranslationJobExtended step(String step) {
    
    
    
    
    this.step = step;
    return this;
  }

   /**
   * The step of the translation job.
   * @return step
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The step of the translation job.")

  public String getStep() {
    return step;
  }


  public void setStep(String step) {
    
    
    
    this.step = step;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TranslationJobExtended instance itself
   */
  public TranslationJobExtended putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranslationJobExtended translationJobExtended = (TranslationJobExtended) o;
    return Objects.equals(this.id, translationJobExtended.id) &&
        Objects.equals(this.videoUrl, translationJobExtended.videoUrl) &&
        Objects.equals(this.audioUrl, translationJobExtended.audioUrl) &&
        Objects.equals(this.transcriptUrl, translationJobExtended.transcriptUrl) &&
        Objects.equals(this.originalVideoUrl, translationJobExtended.originalVideoUrl) &&
        Objects.equals(this.sourceLanguage, translationJobExtended.sourceLanguage) &&
        Objects.equals(this.targetLanguage, translationJobExtended.targetLanguage) &&
        Objects.equals(this.status, translationJobExtended.status) &&
        Objects.equals(this.step, translationJobExtended.step)&&
        Objects.equals(this.additionalProperties, translationJobExtended.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, videoUrl, audioUrl, transcriptUrl, originalVideoUrl, sourceLanguage, targetLanguage, status, step, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranslationJobExtended {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    videoUrl: ").append(toIndentedString(videoUrl)).append("\n");
    sb.append("    audioUrl: ").append(toIndentedString(audioUrl)).append("\n");
    sb.append("    transcriptUrl: ").append(toIndentedString(transcriptUrl)).append("\n");
    sb.append("    originalVideoUrl: ").append(toIndentedString(originalVideoUrl)).append("\n");
    sb.append("    sourceLanguage: ").append(toIndentedString(sourceLanguage)).append("\n");
    sb.append("    targetLanguage: ").append(toIndentedString(targetLanguage)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    step: ").append(toIndentedString(step)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("video_url");
    openapiFields.add("audio_url");
    openapiFields.add("transcript_url");
    openapiFields.add("original_video_url");
    openapiFields.add("source_language");
    openapiFields.add("target_language");
    openapiFields.add("status");
    openapiFields.add("step");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("audio_url");
    openapiRequiredFields.add("original_video_url");
    openapiRequiredFields.add("source_language");
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("step");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TranslationJobExtended
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TranslationJobExtended.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TranslationJobExtended is not found in the empty JSON string", TranslationJobExtended.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TranslationJobExtended.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("video_url") != null && !jsonObj.get("video_url").isJsonNull()) && !jsonObj.get("video_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `video_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("video_url").toString()));
      }
      if (!jsonObj.get("audio_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `audio_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("audio_url").toString()));
      }
      if ((jsonObj.get("transcript_url") != null && !jsonObj.get("transcript_url").isJsonNull()) && !jsonObj.get("transcript_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `transcript_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transcript_url").toString()));
      }
      if (!jsonObj.get("original_video_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `original_video_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("original_video_url").toString()));
      }
      if (!jsonObj.get("source_language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_language").toString()));
      }
      if ((jsonObj.get("target_language") != null && !jsonObj.get("target_language").isJsonNull()) && !jsonObj.get("target_language").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target_language` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target_language").toString()));
      }
      if (!jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("step").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `step` to be a primitive type in the JSON string but got `%s`", jsonObj.get("step").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TranslationJobExtended.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TranslationJobExtended' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TranslationJobExtended> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TranslationJobExtended.class));

       return (TypeAdapter<T>) new TypeAdapter<TranslationJobExtended>() {
           @Override
           public void write(JsonWriter out, TranslationJobExtended value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TranslationJobExtended read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TranslationJobExtended instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TranslationJobExtended given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TranslationJobExtended
  * @throws IOException if the JSON string is invalid with respect to TranslationJobExtended
  */
  public static TranslationJobExtended fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TranslationJobExtended.class);
  }

 /**
  * Convert an instance of TranslationJobExtended to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

