/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AnimateDto;
import com.konfigthis.client.model.AnimateExtended;
import com.konfigthis.client.model.AnimateInitial;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AnimateApi
 */
@Disabled
public class AnimateApiTest {

    private static AnimateApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AnimateApi(apiClient);
    }

    /**
     * 
     *
     * Generates audio given inputted text and voice and synchronizes with the given video.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void animateTest() throws ApiException {
        String videoUrl = null;
        String transcript = null;
        String voiceId = null;
        String model = null;
        Double maxCredits = null;
        String webhookUrl = null;
        AnimateInitial response = api.animate(videoUrl, transcript, voiceId)
                .model(model)
                .maxCredits(maxCredits)
                .webhookUrl(webhookUrl)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void animateCostTest() throws ApiException {
        String transcript = null;
        String transcriptUrl = null;
        api.animateCost()
                .transcript(transcript)
                .transcriptUrl(transcriptUrl)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * Use the ID from the POST request to check status. Keep checking until status is &#39;completed&#39; and a download URL is provided.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAnimationTest() throws ApiException {
        String id = null;
        AnimateExtended response = api.getAnimation(id)
                .execute();
        // TODO: test validations
    }

}
