/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.SpeakDto;
import com.konfigthis.client.model.SpeakExtended;
import com.konfigthis.client.model.SpeakInitial;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SpeakApi
 */
@Disabled
public class SpeakApiTest {

    private static SpeakApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SpeakApi(apiClient);
    }

    /**
     * 
     *
     * Use the video ID from the POST request to check video status. Keep checking until status is &#39;completed&#39; and a download URL is provided.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSpeechTest() throws ApiException {
        String id = null;
        SpeakExtended response = api.getSpeech(id)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void speakTest() throws ApiException {
        String transcript = null;
        String voiceId = null;
        Double maxCredits = null;
        String webhookUrl = null;
        SpeakInitial response = api.speak(transcript, voiceId)
                .maxCredits(maxCredits)
                .webhookUrl(webhookUrl)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void speakCostTest() throws ApiException {
        String transcript = null;
        String transcriptUrl = null;
        api.speakCost()
                .transcript(transcript)
                .transcriptUrl(transcriptUrl)
                .execute();
        // TODO: test validations
    }

}
