/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.TranslateDto;
import com.konfigthis.client.model.TranslationJobExtended;
import com.konfigthis.client.model.TranslationJobInitial;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TranslateApi
 */
@Disabled
public class TranslateApiTest {

    private static TranslateApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TranslateApi(apiClient);
    }

    /**
     * 
     *
     * Use the video ID from the POST request to check video status. Keep checking until status is &#39;completed&#39; and a download URL is provided.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTranslationTest() throws ApiException {
        String id = null;
        TranslationJobExtended response = api.getTranslation(id)
                .execute();
        // TODO: test validations
    }

    /**
     * 
     *
     * Translates and synchronizes the given video to the specified target language.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void translateTest() throws ApiException {
        String videoUrl = null;
        String targetLanguage = null;
        Double maxCredits = null;
        String webhookUrl = null;
        String model = null;
        TranslationJobInitial response = api.translate(videoUrl, targetLanguage)
                .maxCredits(maxCredits)
                .webhookUrl(webhookUrl)
                .model(model)
                .execute();
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void translationCostTest() throws ApiException {
        String videoUrl = null;
        api.translationCost(videoUrl)
                .execute();
        // TODO: test validations
    }

}
