/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.LipSyncExtended;
import com.konfigthis.client.model.LipSyncInitial;
import com.konfigthis.client.model.LipsyncDto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class LipsyncApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public LipsyncApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public LipsyncApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKey() == null) {
            throw new IllegalArgumentException("\"x-api-key\" is required but no API key was provided. Please set \"x-api-key\" with ApiClient#setApiKey(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call getLipsyncCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/lipsync/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLipsyncValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getLipsync(Async)");
        }

        return getLipsyncCall(id, _callback);

    }


    private ApiResponse<LipSyncExtended> getLipsyncWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getLipsyncValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<LipSyncExtended>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getLipsyncAsync(String id, final ApiCallback<LipSyncExtended> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLipsyncValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<LipSyncExtended>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetLipsyncRequestBuilder {
        private final String id;

        private GetLipsyncRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getLipsync
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getLipsyncCall(id, _callback);
        }


        /**
         * Execute getLipsync request
         * @return LipSyncExtended
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         */
        public LipSyncExtended execute() throws ApiException {
            ApiResponse<LipSyncExtended> localVarResp = getLipsyncWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getLipsync request with HTTP info returned
         * @return ApiResponse&lt;LipSyncExtended&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<LipSyncExtended> executeWithHttpInfo() throws ApiException {
            return getLipsyncWithHttpInfo(id);
        }

        /**
         * Execute getLipsync request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<LipSyncExtended> _callback) throws ApiException {
            return getLipsyncAsync(id, _callback);
        }
    }

    /**
     * 
     * Use the video ID from the POST request to check video status. Keep checking until status is &#39;completed&#39; and a download URL is provided.
     * @param id  (required)
     * @return GetLipsyncRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
     </table>
     */
    public GetLipsyncRequestBuilder getLipsync(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetLipsyncRequestBuilder(id);
    }
    private okhttp3.Call lipSyncCall(LipsyncDto lipsyncDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = lipsyncDto;

        // create path and map variables
        String localVarPath = "/lipsync";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call lipSyncValidateBeforeCall(LipsyncDto lipsyncDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'lipsyncDto' is set
        if (lipsyncDto == null) {
            throw new ApiException("Missing the required parameter 'lipsyncDto' when calling lipSync(Async)");
        }

        return lipSyncCall(lipsyncDto, _callback);

    }


    private ApiResponse<LipSyncInitial> lipSyncWithHttpInfo(LipsyncDto lipsyncDto) throws ApiException {
        okhttp3.Call localVarCall = lipSyncValidateBeforeCall(lipsyncDto, null);
        Type localVarReturnType = new TypeToken<LipSyncInitial>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call lipSyncAsync(LipsyncDto lipsyncDto, final ApiCallback<LipSyncInitial> _callback) throws ApiException {

        okhttp3.Call localVarCall = lipSyncValidateBeforeCall(lipsyncDto, _callback);
        Type localVarReturnType = new TypeToken<LipSyncInitial>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class LipSyncRequestBuilder {
        private final String audioUrl;
        private final String videoUrl;
        private final Boolean synergize;
        private Double maxCredits;
        private String webhookUrl;
        private String model;

        private LipSyncRequestBuilder(String audioUrl, String videoUrl, Boolean synergize) {
            this.audioUrl = audioUrl;
            this.videoUrl = videoUrl;
            this.synergize = synergize;
        }

        /**
         * Set maxCredits
         * @param maxCredits Maximum number of credits to use for video generation. If job exceeds this value, the job will be aborted (optional)
         * @return LipSyncRequestBuilder
         */
        public LipSyncRequestBuilder maxCredits(Double maxCredits) {
            this.maxCredits = maxCredits;
            return this;
        }
        
        /**
         * Set webhookUrl
         * @param webhookUrl A url to send a notification to upon completion of video generation (optional)
         * @return LipSyncRequestBuilder
         */
        public LipSyncRequestBuilder webhookUrl(String webhookUrl) {
            this.webhookUrl = webhookUrl;
            return this;
        }
        
        /**
         * Set model
         * @param model The model to use for video generation (optional, default to sync-1.5.0)
         * @return LipSyncRequestBuilder
         */
        public LipSyncRequestBuilder model(String model) {
            this.model = model;
            return this;
        }
        
        /**
         * Build call for lipSync
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            LipsyncDto lipsyncDto = buildBodyParams();
            return lipSyncCall(lipsyncDto, _callback);
        }

        private LipsyncDto buildBodyParams() {
            LipsyncDto lipsyncDto = new LipsyncDto();
            lipsyncDto.audioUrl(this.audioUrl);
            lipsyncDto.videoUrl(this.videoUrl);
            lipsyncDto.synergize(this.synergize);
            lipsyncDto.maxCredits(this.maxCredits);
            lipsyncDto.webhookUrl(this.webhookUrl);
            lipsyncDto.model(this.model);
            return lipsyncDto;
        }

        /**
         * Execute lipSync request
         * @return LipSyncInitial
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public LipSyncInitial execute() throws ApiException {
            LipsyncDto lipsyncDto = buildBodyParams();
            ApiResponse<LipSyncInitial> localVarResp = lipSyncWithHttpInfo(lipsyncDto);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute lipSync request with HTTP info returned
         * @return ApiResponse&lt;LipSyncInitial&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<LipSyncInitial> executeWithHttpInfo() throws ApiException {
            LipsyncDto lipsyncDto = buildBodyParams();
            return lipSyncWithHttpInfo(lipsyncDto);
        }

        /**
         * Execute lipSync request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<LipSyncInitial> _callback) throws ApiException {
            LipsyncDto lipsyncDto = buildBodyParams();
            return lipSyncAsync(lipsyncDto, _callback);
        }
    }

    /**
     * 
     * Submit a set of urls to publically hosted audio and video files or to YouTube videos. Our synchronizer will sync the video&#39;s lip movements to match the audio and return the synced video.
     * @param lipsyncDto The audio + video data to be synced. Set synergize &#x3D; false to skip our synergizer post-processor for a 10x speedup, but w/ a degredation in output quality. (required)
     * @return LipSyncRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public LipSyncRequestBuilder lipSync(String audioUrl, String videoUrl, Boolean synergize) throws IllegalArgumentException {
        if (audioUrl == null) throw new IllegalArgumentException("\"audioUrl\" is required but got null");
            

        if (videoUrl == null) throw new IllegalArgumentException("\"videoUrl\" is required but got null");
            

        if (synergize == null) throw new IllegalArgumentException("\"synergize\" is required but got null");
        return new LipSyncRequestBuilder(audioUrl, videoUrl, synergize);
    }
    private okhttp3.Call lipsyncCostCall(String audioUrl, String videoUrl, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/lipsync/cost";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (audioUrl != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("audioUrl", audioUrl));
        }

        if (videoUrl != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("videoUrl", videoUrl));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call lipsyncCostValidateBeforeCall(String audioUrl, String videoUrl, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'audioUrl' is set
        if (audioUrl == null) {
            throw new ApiException("Missing the required parameter 'audioUrl' when calling lipsyncCost(Async)");
        }

        // verify the required parameter 'videoUrl' is set
        if (videoUrl == null) {
            throw new ApiException("Missing the required parameter 'videoUrl' when calling lipsyncCost(Async)");
        }

        return lipsyncCostCall(audioUrl, videoUrl, _callback);

    }


    private ApiResponse<Void> lipsyncCostWithHttpInfo(String audioUrl, String videoUrl) throws ApiException {
        okhttp3.Call localVarCall = lipsyncCostValidateBeforeCall(audioUrl, videoUrl, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call lipsyncCostAsync(String audioUrl, String videoUrl, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = lipsyncCostValidateBeforeCall(audioUrl, videoUrl, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class LipsyncCostRequestBuilder {
        private final String audioUrl;
        private final String videoUrl;

        private LipsyncCostRequestBuilder(String audioUrl, String videoUrl) {
            this.audioUrl = audioUrl;
            this.videoUrl = videoUrl;
        }

        /**
         * Build call for lipsyncCost
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return lipsyncCostCall(audioUrl, videoUrl, _callback);
        }


        /**
         * Execute lipsyncCost request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public void execute() throws ApiException {
            lipsyncCostWithHttpInfo(audioUrl, videoUrl);
        }

        /**
         * Execute lipsyncCost request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return lipsyncCostWithHttpInfo(audioUrl, videoUrl);
        }

        /**
         * Execute lipsyncCost request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return lipsyncCostAsync(audioUrl, videoUrl, _callback);
        }
    }

    /**
     * 
     * 
     * @param audioUrl A url to the audio file to be synchronized -- must be publicly accessible (required)
     * @param videoUrl A url to the video file to be synchronized -- must be publicly accessible (required)
     * @return LipsyncCostRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public LipsyncCostRequestBuilder lipsyncCost(String audioUrl, String videoUrl) throws IllegalArgumentException {
        if (audioUrl == null) throw new IllegalArgumentException("\"audioUrl\" is required but got null");
            

        if (videoUrl == null) throw new IllegalArgumentException("\"videoUrl\" is required but got null");
            

        return new LipsyncCostRequestBuilder(audioUrl, videoUrl);
    }
}
