/*
 * Synchronize API
 * Synchronize API allows you to lipsync a video to any audio in any language.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.CreateVideoDto;
import com.konfigthis.client.model.VideoExtended;
import com.konfigthis.client.model.VideoInitial;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class VideoApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public VideoApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public VideoApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        if (apiClient.getApiKey() == null) {
            throw new IllegalArgumentException("\"x-api-key\" is required but no API key was provided. Please set \"x-api-key\" with ApiClient#setApiKey(String).");
        }
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call costCall(String audioUrl, String videoUrl, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/video/cost";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (audioUrl != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("audioUrl", audioUrl));
        }

        if (videoUrl != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("videoUrl", videoUrl));
        }

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @Deprecated
    @SuppressWarnings("rawtypes")
    private okhttp3.Call costValidateBeforeCall(String audioUrl, String videoUrl, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'audioUrl' is set
        if (audioUrl == null) {
            throw new ApiException("Missing the required parameter 'audioUrl' when calling cost(Async)");
        }

        // verify the required parameter 'videoUrl' is set
        if (videoUrl == null) {
            throw new ApiException("Missing the required parameter 'videoUrl' when calling cost(Async)");
        }

        return costCall(audioUrl, videoUrl, _callback);

    }


    private ApiResponse<Void> costWithHttpInfo(String audioUrl, String videoUrl) throws ApiException {
        okhttp3.Call localVarCall = costValidateBeforeCall(audioUrl, videoUrl, null);
        return localVarApiClient.execute(localVarCall);
    }

    private okhttp3.Call costAsync(String audioUrl, String videoUrl, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = costValidateBeforeCall(audioUrl, videoUrl, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }

    public class CostRequestBuilder {
        private final String audioUrl;
        private final String videoUrl;

        private CostRequestBuilder(String audioUrl, String videoUrl) {
            this.audioUrl = audioUrl;
            this.videoUrl = videoUrl;
        }

        /**
         * Build call for cost
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return costCall(audioUrl, videoUrl, _callback);
        }


        /**
         * Execute cost request
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public void execute() throws ApiException {
            costWithHttpInfo(audioUrl, videoUrl);
        }

        /**
         * Execute cost request with HTTP info returned
         * @return ApiResponse&lt;Void&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public ApiResponse<Void> executeWithHttpInfo() throws ApiException {
            return costWithHttpInfo(audioUrl, videoUrl);
        }

        /**
         * Execute cost request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call executeAsync(final ApiCallback<Void> _callback) throws ApiException {
            return costAsync(audioUrl, videoUrl, _callback);
        }
    }

    /**
     * 
     * 
     * @param audioUrl A url to the audio file to be synchronized -- must be publicly accessible (required)
     * @param videoUrl A url to the video file to be synchronized -- must be publicly accessible (required)
     * @return CostRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public CostRequestBuilder cost(String audioUrl, String videoUrl) throws IllegalArgumentException {
        if (audioUrl == null) throw new IllegalArgumentException("\"audioUrl\" is required but got null");
            

        if (videoUrl == null) throw new IllegalArgumentException("\"videoUrl\" is required but got null");
            

        return new CostRequestBuilder(audioUrl, videoUrl);
    }
    private okhttp3.Call getLipSyncJobCall(String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/video/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @Deprecated
    @SuppressWarnings("rawtypes")
    private okhttp3.Call getLipSyncJobValidateBeforeCall(String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling getLipSyncJob(Async)");
        }

        return getLipSyncJobCall(id, _callback);

    }


    private ApiResponse<VideoExtended> getLipSyncJobWithHttpInfo(String id) throws ApiException {
        okhttp3.Call localVarCall = getLipSyncJobValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<VideoExtended>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call getLipSyncJobAsync(String id, final ApiCallback<VideoExtended> _callback) throws ApiException {

        okhttp3.Call localVarCall = getLipSyncJobValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<VideoExtended>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class GetLipSyncJobRequestBuilder {
        private final String id;

        private GetLipSyncJobRequestBuilder(String id) {
            this.id = id;
        }

        /**
         * Build call for getLipSyncJob
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            return getLipSyncJobCall(id, _callback);
        }


        /**
         * Execute getLipSyncJob request
         * @return VideoExtended
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public VideoExtended execute() throws ApiException {
            ApiResponse<VideoExtended> localVarResp = getLipSyncJobWithHttpInfo(id);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute getLipSyncJob request with HTTP info returned
         * @return ApiResponse&lt;VideoExtended&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public ApiResponse<VideoExtended> executeWithHttpInfo() throws ApiException {
            return getLipSyncJobWithHttpInfo(id);
        }

        /**
         * Execute getLipSyncJob request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call executeAsync(final ApiCallback<VideoExtended> _callback) throws ApiException {
            return getLipSyncJobAsync(id, _callback);
        }
    }

    /**
     * 
     * [Deprecated] Use the video ID from the POST request to check video status. Keep checking until status is &#39;completed&#39; and a download URL is provided.
     * @param id  (required)
     * @return GetLipSyncJobRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td> Returns video status and URL to download from. </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public GetLipSyncJobRequestBuilder getLipSyncJob(String id) throws IllegalArgumentException {
        if (id == null) throw new IllegalArgumentException("\"id\" is required but got null");
            

        return new GetLipSyncJobRequestBuilder(id);
    }
    private okhttp3.Call lipSyncCall(CreateVideoDto createVideoDto, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createVideoDto;

        // create path and map variables
        String localVarPath = "/video";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "apiKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @Deprecated
    @SuppressWarnings("rawtypes")
    private okhttp3.Call lipSyncValidateBeforeCall(CreateVideoDto createVideoDto, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createVideoDto' is set
        if (createVideoDto == null) {
            throw new ApiException("Missing the required parameter 'createVideoDto' when calling lipSync(Async)");
        }

        return lipSyncCall(createVideoDto, _callback);

    }


    private ApiResponse<VideoInitial> lipSyncWithHttpInfo(CreateVideoDto createVideoDto) throws ApiException {
        okhttp3.Call localVarCall = lipSyncValidateBeforeCall(createVideoDto, null);
        Type localVarReturnType = new TypeToken<VideoInitial>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call lipSyncAsync(CreateVideoDto createVideoDto, final ApiCallback<VideoInitial> _callback) throws ApiException {

        okhttp3.Call localVarCall = lipSyncValidateBeforeCall(createVideoDto, _callback);
        Type localVarReturnType = new TypeToken<VideoInitial>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class LipSyncRequestBuilder {
        private final String audioUrl;
        private final String videoUrl;
        private final Boolean synergize;
        private Double maxCredits;
        private String webhookUrl;
        private String model;

        private LipSyncRequestBuilder(String audioUrl, String videoUrl, Boolean synergize) {
            this.audioUrl = audioUrl;
            this.videoUrl = videoUrl;
            this.synergize = synergize;
        }

        /**
         * Set maxCredits
         * @param maxCredits Maximum number of credits to use for video generation. If job exceeds this value, the job will be aborted (optional)
         * @return LipSyncRequestBuilder
         */
        public LipSyncRequestBuilder maxCredits(Double maxCredits) {
            this.maxCredits = maxCredits;
            return this;
        }
        
        /**
         * Set webhookUrl
         * @param webhookUrl A url to send a notification to upon completion of video generation (optional)
         * @return LipSyncRequestBuilder
         */
        public LipSyncRequestBuilder webhookUrl(String webhookUrl) {
            this.webhookUrl = webhookUrl;
            return this;
        }
        
        /**
         * Set model
         * @param model The model to use for video generation (optional, default to sync-1.5.0)
         * @return LipSyncRequestBuilder
         */
        public LipSyncRequestBuilder model(String model) {
            this.model = model;
            return this;
        }
        
        /**
         * Build call for lipSync
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateVideoDto createVideoDto = buildBodyParams();
            return lipSyncCall(createVideoDto, _callback);
        }

        private CreateVideoDto buildBodyParams() {
            CreateVideoDto createVideoDto = new CreateVideoDto();
            createVideoDto.audioUrl(this.audioUrl);
            createVideoDto.videoUrl(this.videoUrl);
            createVideoDto.synergize(this.synergize);
            createVideoDto.maxCredits(this.maxCredits);
            createVideoDto.webhookUrl(this.webhookUrl);
            createVideoDto.model(this.model);
            return createVideoDto;
        }

        /**
         * Execute lipSync request
         * @return VideoInitial
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public VideoInitial execute() throws ApiException {
            CreateVideoDto createVideoDto = buildBodyParams();
            ApiResponse<VideoInitial> localVarResp = lipSyncWithHttpInfo(createVideoDto);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute lipSync request with HTTP info returned
         * @return ApiResponse&lt;VideoInitial&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public ApiResponse<VideoInitial> executeWithHttpInfo() throws ApiException {
            CreateVideoDto createVideoDto = buildBodyParams();
            return lipSyncWithHttpInfo(createVideoDto);
        }

        /**
         * Execute lipSync request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
         </table>
         * @deprecated
         */
        @Deprecated
        public okhttp3.Call executeAsync(final ApiCallback<VideoInitial> _callback) throws ApiException {
            CreateVideoDto createVideoDto = buildBodyParams();
            return lipSyncAsync(createVideoDto, _callback);
        }
    }

    /**
     * 
     * [Deprecated] Submit a set of urls to publically hosted audio and video files or to YouTube videos. Our synchronizer will sync the video&#39;s lip movements to match the audio and return the synced video.
     * @param createVideoDto The audio + video data to be synced. Set synergize &#x3D; false to skip our synergizer post-processor for a 10x speedup, but w/ a degredation in output quality. (required)
     * @return LipSyncRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 0 </td><td>  </td><td>  -  </td></tr>
     </table>
     * @deprecated
     */
    @Deprecated
    public LipSyncRequestBuilder lipSync(String audioUrl, String videoUrl, Boolean synergize) throws IllegalArgumentException {
        if (audioUrl == null) throw new IllegalArgumentException("\"audioUrl\" is required but got null");
            

        if (videoUrl == null) throw new IllegalArgumentException("\"videoUrl\" is required but got null");
            

        if (synergize == null) throw new IllegalArgumentException("\"synergize\" is required but got null");
        return new LipSyncRequestBuilder(audioUrl, videoUrl, synergize);
    }
}
